#include <C:/LB1_MC/Laboratory_Practice/Laboratory_Practice/Core/Inc/init.h>

void GPIO_Init(void) 
{
    //Включение тактирования портов GPIOA|GPIOB|GPIOC
    
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN);

    SET_BIT(GPIOA->MODER, GPIO_MODER_MODE0_0);
    SET_BIT(GPIOA->MODER, GPIO_MODER_MODE1_0);
    SET_BIT(GPIOA->MODER, GPIO_MODER_MODE4_0);

    CLEAR_BIT(GPIOA->OTYPER, GPIO_OTYPER_OT0);
    CLEAR_BIT(GPIOA->OTYPER, GPIO_OTYPER_OT1);
    CLEAR_BIT(GPIOA->OTYPER, GPIO_OTYPER_OT4);

    SET_BIT(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);
    SET_BIT(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEEDR1_0);
    SET_BIT(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEEDR4_0);

    SET_BIT(GPIOA->PUPDR, GPIO_PUPDR_PUPD0);
    SET_BIT(GPIOA->PUPDR, GPIO_PUPDR_PUPD1);
    SET_BIT(GPIOA->PUPDR, GPIO_PUPDR_PUPD4);
}